### ISSUE TITLE
Social-app-core dependency no longer Python 2.7 compatible

### ISSUE THREAD

**Issue by goneall** [python-social-auth/social-app-django#296]
### Expected behaviour

A dependency requirement on a specific version of social-app-django is expected to continue to work on the same version of Python.

For example: `social-auth-app-django==3.4.0` on Python version 2.7 would be expected to install without issue.

### Actual behaviour

After release [social-auth-core release 4.0.3](https://github.com/python-social-auth/social-core/releases/tag/4.0.3), installation of this dependency yields the following error from `pip install`:

```
ERROR: Could not find a version that satisfies the requirement PyJWT>=2.0.0 (from social-auth-core>=3.3.0->social-auth-app-django==3.4.0->-r requirements.txt (line 8)) (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 1.0.0, 1.0.1, 1.1.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.3, 1.6.4, 1.7.0, 1.7.1)
ERROR: No matching distribution found for PyJWT>=2.0.0 (from social-auth-core>=3.3.0->social-auth-app-django==3.4.0->-r requirements.txt (line 8))
```
### What are the steps to reproduce this issue?

1. Create a Python 2.7 environment (e.g. a virtualenv)
2. `pip install social-auth-app-django==3.4.0`

### Any other comments?

Note that this issue was initially discovered in installing the spdx-online-tools which as social-app-django as a dependency.  See https://github.com/spdx/spdx-online-tools/issues/284 for reference.

The [dependency ](https://github.com/python-social-auth/social-app-django/blob/ebd9a19efd8577e72debaf0b098a4cfd569ec731/requirements.txt#L1)on social-auth-core currently states `social-auth-core >= 4.0.2`

This could be changed to:
```
social-auth-core == 4.0.2,  python_version < '3.0'
social-auth-core >= 4.0.3,  python_version >= '3.0'
```

**Comment by nijel** [comment]
Support for Python 2 has been dropped in the 4.x series. The early releases might still work with it, but it's not tested or officially supported. Starting with 4.0.3 it's not possible to install on Python 2 due to dependencies. The upcoming releases will completely drop compatibility code for Python 2 (see for example https://github.com/python-social-auth/social-app-django/commit/9b4075ae3abf883ae5eaa1a44edf30a916be6d41) and will be marked as Python 3 only (see https://github.com/python-social-auth/social-app-django/commit/08d2380956715461df54aedadf1d647275f80c1e).

If you are still using Python 2 (which is no longer supported upstream), use an older version of the library.

**Comment by goneall** [comment]
@nijel Thanks for the info.  It is definitely time to move to Python 3 (a significant project we have underway).

> If you are still using Python 2 (which is no longer supported upstream), use an older version of the library.

Just FYI - since the earlier versions of the library have the dependency specified as `social-auth-core >= X.YY.ZZ`, it will pick up the latest social-auth-core which is incompatible.  From what I understand, this can be worked around by specifying the social-auth-core version before the social-app-django dependency declaration.
