### ISSUE TITLE
Missing migrations in v5.1.0 ?

### ISSUE THREAD

**Issue by jedie** [python-social-auth/social-app-django#429]
Seems that migrations needed for v5.1.0, but not added.

I see this:

```
  .../lib/python3.10/site-packages/social_django/migrations/0012_alter_association_id_alter_code_id_alter_nonce_id_and_more.py
    - Alter field id on association
    - Alter field id on code
    - Alter field id on nonce
    - Alter field id on partial
    - Alter field id on usersocialauth
```

I would suggest adding a test for missing migrations, e.g.:
```python
    def test_missing_migrations(self):
        output = io.StringIO()
        try:
            management.call_command(
                makemigrations.Command(),
                dry_run=True,
                check_changes=True,
                verbosity=1,
                stdout=output,
                no_color=True,
            )
        except SystemExit as err:
            if err.code != 0:
                raise AssertionError(output.getvalue())
```

**Comment by jedie** [comment]
To late i already made: https://github.com/python-social-auth/social-app-django/pull/430 ...

**Comment by gabrielfgularte** [comment]
Hi folks, any workaround here?

My Django `checkmigrations` step is always failing.

Thanks!

**Comment by james-certn** [comment]
📢  Hi all, to add clarity to this issue:

- @gabrielfgularte's comment around `makemigrations --check` failing is due to [Django 4.x's change to the migration autodetector](https://docs.djangoproject.com/en/4.1/releases/4.0/#migrations-autodetector-changes)
  - Indeed, no-op migrations are created when running `makemigrations` (I see this with a local `venv` virtual environment with social_django installed)
  - `makemigrations --check` doesn't _appear_ to fail by output, however the exit code is `1` (after running the command, run `echo $?` to see the exit code)
- The two PRs mentioned above are created with different versions of Django
  - [396](https://github.com/python-social-auth/social-app-django/pull/396/files) is created with 3.x - this means this migration will likely still fail `makemigrations --check` for 4.x users
  - [430](https://github.com/python-social-auth/social-app-django/pull/430/files) is created with 4.x - this migration should work for all users (3.x, 4.x, etc)

### **If the `BigAutoField` changes are required, I'd recommend regenerating them using a 4.x installation.**

**Comment by atodorov** [comment]
@nijel now that this is closed are you planning a new PyPI release soon ? I think it would resolve a lot of issues folks are having with the migrations.

**Comment by nijel** [comment]
Yes, once we fix and release core so that it can depend on fixed version there as well.

**Comment by GithubWikiRealty** [comment]
so in the meantime we wait for the release, what could be a safe workaround? are these missing migration breaking anything? I been seeing the warning from Django but things seems to be working normally, i have `social-app-django` as a dependency of `rest-social-auth`

Thanks

**Comment by luiscastillocr** [comment]
so in the meantime we wait for the release, what could be a safe workaround? are these missing migration breaking anything? I been seeing the warning from Django but things seems to be working normally, i have social-app-django as a dependency of rest-social-auth

Thanks

**Comment by nijel** [comment]
It is not really a missing migration (see https://github.com/python-social-auth/social-app-django/commit/919978877c349585006438654b13cef3974511d5), it's harmless. It's just caused by the change in Django handling of primary keys.

PS: The release will be out today.

**Comment by luiscastillocr** [comment]
Excellent news!

Thank you!
