### ISSUE TITLE
Prepare app for Django 2.0

### ISSUE THREAD

**Issue by omab** [python-social-auth/social-app-django#6]
This issue will collect all the needed details to prepare the app to support for Django 2.0.

**Comment by omab** [comment]
`2.0` comes on 2018, no hurries on this yet.

**Comment by omab** [comment]
Roadmap points that Django 2.0 comes on Dec 2017.

**Comment by RevolutionTech** [comment]
Line 62 of `models.py` uses `field.rel`:
https://github.com/python-social-auth/social-app-django/blob/e368f5305ecb469ae0908b0fa24b8c1797d3d22c/social_django/models.py#L62

This causes a warning in Django 1.9, but in Django 2.0 this code will cease to work.

On a related note, `ForeignObjectRel.to` was deprecated in favour of the model attribute.
Original exception message: `Usage of ForeignObjectRel.to attribute has been deprecated. Use the model attribute instead`.

Ref: https://docs.djangoproject.com/en/1.9/releases/1.9/#field-rel-changes

**Comment by andreif** [comment]
@RevolutionTech @omab Hi, could you please have a look at #89? I tried to make as little changes as possible there and at the same time increased the test coverage. The mentioned issue with `ForeignObjectRel.to` is now fixed and tested. I am going to open more PRs for improving test coverage, but I need to get this one merged first since it prepares the ground for other tests.

**Comment by coler-j** [comment]
Is this not done yet? Django 2.0 has been out for a long time now.

**Comment by thelittlebug** [comment]
> The web framework for perfectionists with deadlines.

aha...

> 640 kB ought to be enough for anybody

so so...

> 2.0 comes on 2018, no hurries on this yet.

aha... :D

**Comment by omab** [comment]
I don't see anything pending on this topic. Reopen the ticket or open new reports with what's failing on Django 2.0.
